#pragma once
#include <iostream>
#include <string>
#include <GL/glew.h>
#include <GLFW\glfw3.h>
#include <GLU/Context.hpp>
#include <GLU/DebugCallback.hpp>
#include <GLU/ElementBuffer.hpp>
#include <GLU/VertexBuffer.hpp>
#include <GLU/Shader.hpp>
#include <GLU/VertexArray.hpp>
