#pragma once
#include <iostream>
#include <string>
#include <GL/glew.h>
#include <GLFW\glfw3.h>
#include <GLU/gluContext.hpp>
#include <GLU/DebugCallback.hpp>
#include <GLU/EBO.hpp>
#include <GLU/VBO.hpp>
#include <GLU/Shader.hpp>
#include <GLU/VAO.hpp>
